version: '3.1'
services:
  db-woodpecker:
    image: postgres:13
    container_name: "test_db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password










